spring:
  datasource:
    url: jdbc:mysql://mysql:3306/harucut?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: redis
      port: 6379
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: 3aa97b22070ce3fe760c6c5d58b626a5
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://api.harucut.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - openid
          naver:
            client-name: naver
            client-id: 0Teu3188i_OJaPcgPwa8
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: https://api.harucut.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
              - profile_image

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1d
  refresh-expiration: 14d
  session-refresh-expiration: 1d

redirect-url:
  frontend: https://harucut.com

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket-name: harucuts3
    bucket-url: https://harucuts3.s3.ap-northeast-2.amazonaws.com/
    region: ap-northeast-2
  mediaconvert:
    role-arn: arn:aws:iam::923246546766:role/harucut-mediaconvert
    template-name: WebM_to_MP4_Template
    endpoint: https://mediaconvert.ap-northeast-2.amazonaws.com
