# 공통 설정
spring:
  application:
    name: harucut
  profiles:
    default: local

  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Seoul

jwt:
  access-expiration: 30m
  refresh-expiration: 14d

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true